[package]
name = "ztxqq"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
log = "0.4.28"
num_cpus = "1.17.0"
tokio = { version = "1.47.1", features = ["full"] }
zetax_types = "0.1.0"
ztx = "1.0.0"
